name: Build
on:
  push:

jobs:
  py-test:
    runs-on: ubuntu-latest
    # Timeout to protect against flaky tests locking up. Fine to extend
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Python dependencies
        run: |
          poetry install
          poetry shell
      - name: Lint
        run: make lint
      - name: Test
        run: make test
